### ISSUE TITLE
plan milestones

### ISSUE THREAD

**Issue by rcrath** [digiah/cortext#2]
@damg70 and @rcrath need to plan this, invite @kljolly, Puakea, and  Noelani A to participate.  [Tea](https://github.com/digiah/2do/issues/121)?

**Comment by damg70** [comment]
design document that translates white board is now in the repo - both as vue graph and word outline

**Comment by damg70** [comment]
@rcrath 
milestone: alpha version!
milestone 1.a: convene working partners
milestone 1.b: extract appropriate code from existing projects (noelle, karen, etc)
milestone 1.c integrate code into alpha version
